//
//  Mentor.swift
//  ScienceStudentSuccessCentre
//
//  Created by Avery Vine on 2019-11-07.
//  Copyright © 2019 Avery Vine. All rights reserved.
//

import Foundation

/// Encompass all of the details for an SSSC mentor.
///
/// - Attention: You should never have to generate these yourself, as mentor generation is handled by the server.
class Mentor {
    private var id: String
    private var name: String
    private var url: URL?
    private var degree: String
    private var bio: String
    private var imageUrl: URL?
    private var team: String
    
    /// Initializes a mentor based off a dictionary of data provided by the server.
    ///
    /// - Parameter mentorData: The data parsed and generated by the server for this mentor.
    required convenience init?(mentorData: NSDictionary) {
        guard let id = mentorData["id"] as? String,
            let name = mentorData["name"] as? String,
            let degree = mentorData["degree"] as? String,
            let bio = mentorData["bio"] as? String,
            let team = mentorData["team"] as? String else {
                return nil
        }
        
        let url: URL?
        if let urlString = mentorData["url"] as? String, urlString != "" {
            url = URL(string: urlString)
        } else {
            url = nil
        }
        
        let imageUrl: URL?
        if let imageUrlString = mentorData["imageUrl"] as? String, imageUrlString != "" {
            imageUrl = URL(string: imageUrlString)
        } else {
            imageUrl = nil
        }
        
        
        self.init(id: id, name: name, url: url, degree: degree, bio: bio, imageUrl: imageUrl, team: team)
    }
    
    private init(id: String, name: String, url: URL?, degree: String,
                 bio: String, imageUrl: URL?, team: String) {
        self.id = id
        self.name = name
        self.url = url
        self.degree = degree
        self.bio = bio
        self.imageUrl = imageUrl
        self.team = team
    }

    /// Gets the id of the mentor.
    ///
    /// - Remark: Note that this id can technically not be unique (as it is just whatever is sent by the server), but should be treated as such.
    /// - Returns: The id of the mentor.
    public func getId() -> String {
        return id
    }
    
    /// Gets the name of the mentor.
    ///
    /// - Returns: The name of the mentor.
    public func getName() -> String {
        return name
    }
    
    /// Gets the complete URL of the mentor, including the domain name portion.
    ///
    /// - Returns: The complete mentor URL, or `nil` if there one could not be found.
    public func getUrl() -> URL? {
        return url
    }
    
    /// Gets the degree of the mentor.
    ///
    /// - Returns: The degree/program of the mentor.
    public func getDegree() -> String {
        return degree
    }
    
    
    /// Gets the bio of the mentor.
    ///
    /// - Returns: The bio of the mentor.
    public func getBio() -> String {
        return bio
    }
    
    /// Gets the URL of the image associated with this mentor.
    ///
    /// - Returns: The image URL, or `nil` if there isn't one associated with this mentor.
    public func getImageUrl() -> URL? {
        return imageUrl
    }
    
    /// Gets the team of the mentor.
    ///
    /// - Returns: The team of the mentor.
    public func getTeam() -> String {
        return team
    }
}
