//
//  Mentor.swift
//  ScienceStudentSuccessCentre
//
//  Created by Avery Vine on 2019-11-07.
//  Copyright © 2019 Avery Vine. All rights reserved.
//

import PromiseKit
import UIKit

/// Encompass all of the details for an SSSC mentor.
///
/// - Attention: You should never have to generate these yourself, as mentor generation is handled by the server.
class Mentor {
    var id: String
    var name: String
    var url: URL?
    var degree: String
    var bio: String
    var team: String
    
    func getImage() -> Guarantee<UIImage?> {
        return Guarantee { seal in
            if cachedImage == nil {
                if let url = imageUrl {
                    if let data = try? Data(contentsOf: url) {
                        cachedImage = UIImage(data: data)
                    }
                }
            }
            seal(cachedImage)
        }
    }
    private var imageUrl: URL?
    private var cachedImage: UIImage?
    
    /// Initializes a mentor based off a dictionary of data provided by the server.
    ///
    /// - Parameter mentorData: The data parsed and generated by the server for this mentor.
    required convenience init?(mentorData: NSDictionary) {
        guard let id = mentorData["id"] as? String,
            let name = mentorData["name"] as? String,
            let degree = mentorData["degree"] as? String,
            let bio = mentorData["bio"] as? String,
            let team = mentorData["team"] as? String else {
                return nil
        }
        
        let url: URL?
        if let urlString = mentorData["url"] as? String, urlString != "" {
            url = URL(string: urlString)
        } else {
            url = nil
        }
        
        let imageUrl: URL?
        if let imageUrlString = mentorData["imageUrl"] as? String, imageUrlString != "" {
            imageUrl = URL(string: imageUrlString)
        } else {
            imageUrl = nil
        }
        
        self.init(id: id, name: name, url: url, degree: degree, bio: bio, imageUrl: imageUrl, team: team)
    }
    
    private init(id: String, name: String, url: URL?, degree: String,
                 bio: String, imageUrl: URL?, team: String) {
        self.id = id
        self.name = name
        self.url = url
        self.degree = degree
        self.bio = bio
        self.imageUrl = imageUrl
        self.team = team
    }
}
